//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 04:11:07 PM MDT 
//


package com.echostar.model.asset.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for MetadataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetadataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AMS" type="{}AMSType"/>
 *         &lt;element name="App_Data" type="{}App_DataType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace="MetadataType1", name = "MetadataType", propOrder = {
    "ams",
    "appData"
})
public class MetadataType {

    @XmlElement(name = "AMS", required = true)
    protected AMSType ams;
    @XmlElement(name = "App_Data", required = true)
    protected List<AppDataType> appData;

    /**
     * Gets the value of the ams property.
     * 
     * @return
     *     possible object is
     *     {@link AMSType }
     *     
     */
    public AMSType getAMS() {
        return ams;
    }

    /**
     * Sets the value of the ams property.
     * 
     * @param value
     *     allowed object is
     *     {@link AMSType }
     *     
     */
    public void setAMS(AMSType value) {
        this.ams = value;
    }

    /**
     * Gets the value of the appData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppDataType }
     * 
     * 
     */
    public List<AppDataType> getAppData() {
        if (appData == null) {
            appData = new ArrayList<AppDataType>();
        }
        return this.appData;
    }

}
