//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 04:11:07 PM MDT 
//


package com.echostar.model.asset.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.echostar.model.asset.jaxb.CustomType.Metadata;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.echostar.model.asset.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ADI_QNAME = new QName("", "ADI");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.echostar.model.asset.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssetPackageType }
     * 
     */
    public AssetPackageType createAssetPackageType() {
        return new AssetPackageType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link AssetWithinAssetType }
     * 
     */
    public AssetWithinAssetType createAssetWithinAssetType() {
        return new AssetWithinAssetType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link ADIType }
     * 
     */
    public ADIType createADIType() {
        return new ADIType();
    }

    /**
     * Create an instance of {@link CustomAppDataType }
     * 
     */
    public CustomAppDataType createCustomAppDataType() {
        return new CustomAppDataType();
    }

    /**
     * Create an instance of {@link AppDataType }
     * 
     */
    public AppDataType createAppDataType() {
        return new AppDataType();
    }

    /**
     * Create an instance of {@link CustomType }
     * 
     */
    public CustomType createCustomType() {
        return new CustomType();
    }

    /**
     * Create an instance of {@link AMSType }
     * 
     */
    public AMSType createAMSType() {
        return new AMSType();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createCustomTypeMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ADIType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADI")
    public JAXBElement<ADIType> createADI(ADIType value) {
        return new JAXBElement<ADIType>(_ADI_QNAME, ADIType.class, null, value);
    }

}
