//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 03:47:41 PM GMT 
//


package com.echostar.model.partialVodAssets.jaxb;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for freshness complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="freshness">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://commons.model.xml.moviedata.vod.iptv.cts.bell.com>tomato">
 *       &lt;attribute name="originalScore" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "freshness", namespace = "http://commons.model.xml.moviedata.vod.iptv.cts.bell.com", propOrder = {
    "value"
})
public class Freshness implements Serializable {

    @XmlValue
    protected Tomato value;
    @XmlAttribute
    protected String originalScore;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Tomato }
     *     
     */
    public Tomato getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tomato }
     *     
     */
    public void setValue(Tomato value) {
        this.value = value;
    }

    /**
     * Gets the value of the originalScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalScore() {
        return originalScore;
    }

    /**
     * Sets the value of the originalScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalScore(String value) {
        this.originalScore = value;
    }

}
