//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 03:47:41 PM GMT 
//


package com.echostar.model.partialVodAssets.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.echostar.model.partialVodAssets.jaxb.Movie.AlternateIds;
import com.echostar.model.partialVodAssets.jaxb.Movie.DvdReleaseDates;
import com.echostar.model.partialVodAssets.jaxb.Movie.Posters;
import com.echostar.model.partialVodAssets.jaxb.Movie.SimilarMovies;
import com.echostar.model.partialVodAssets.jaxb.Movie.TheaterReleaseDates;
import com.echostar.model.partialVodAssets.jaxb.Movie.Urls;


/**
 * <p>Java class for movie complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="movie">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rating" type="{}mpaaRating" minOccurs="0"/>
 *         &lt;element name="releaseYear" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="urls" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="url" type="{}typedUrl" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="alternateIds" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{}typedString" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="similarMovies" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="posters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="poster" type="{}sizedUrl" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cast" type="{}castList" minOccurs="0"/>
 *         &lt;element name="theaterReleaseDates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="theaterReleaseDate" type="{}releaseDate" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dvdReleaseDates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dvdReleaseDate" type="{}releaseDate" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="criticSummary" type="{}criticSummary" minOccurs="0"/>
 *         &lt;element name="fanSummary" type="{}fanSummary" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "movie", propOrder = {
    "title",
    "rating",
    "releaseYear",
    "urls",
    "alternateIds",
    "similarMovies",
    "posters",
    "cast",
    "theaterReleaseDates",
    "dvdReleaseDates",
    "criticSummary",
    "fanSummary"
})
public class Movie implements Serializable {

    protected String title;
    protected MpaaRating rating;
    protected XMLGregorianCalendar releaseYear;
    protected Urls urls;
    protected AlternateIds alternateIds;
    protected SimilarMovies similarMovies;
    protected Posters posters;
    protected CastList cast;
    protected TheaterReleaseDates theaterReleaseDates;
    protected DvdReleaseDates dvdReleaseDates;
    protected CriticSummary criticSummary;
    protected FanSummary fanSummary;
    @XmlAttribute(required = true)
    protected long id;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link MpaaRating }
     *     
     */
    public MpaaRating getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link MpaaRating }
     *     
     */
    public void setRating(MpaaRating value) {
        this.rating = value;
    }

    /**
     * Gets the value of the releaseYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReleaseYear() {
        return releaseYear;
    }

    /**
     * Sets the value of the releaseYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReleaseYear(XMLGregorianCalendar value) {
        this.releaseYear = value;
    }

    /**
     * Gets the value of the urls property.
     * 
     * @return
     *     possible object is
     *     {@link Urls }
     *     
     */
    public Urls getUrls() {
        return urls;
    }

    /**
     * Sets the value of the urls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Urls }
     *     
     */
    public void setUrls(Urls value) {
        this.urls = value;
    }

    /**
     * Gets the value of the alternateIds property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateIds }
     *     
     */
    public AlternateIds getAlternateIds() {
        return alternateIds;
    }

    /**
     * Sets the value of the alternateIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateIds }
     *     
     */
    public void setAlternateIds(AlternateIds value) {
        this.alternateIds = value;
    }

    /**
     * Gets the value of the similarMovies property.
     * 
     * @return
     *     possible object is
     *     {@link SimilarMovies }
     *     
     */
    public SimilarMovies getSimilarMovies() {
        return similarMovies;
    }

    /**
     * Sets the value of the similarMovies property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimilarMovies }
     *     
     */
    public void setSimilarMovies(SimilarMovies value) {
        this.similarMovies = value;
    }

    /**
     * Gets the value of the posters property.
     * 
     * @return
     *     possible object is
     *     {@link Posters }
     *     
     */
    public Posters getPosters() {
        return posters;
    }

    /**
     * Sets the value of the posters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Posters }
     *     
     */
    public void setPosters(Posters value) {
        this.posters = value;
    }

    /**
     * Gets the value of the cast property.
     * 
     * @return
     *     possible object is
     *     {@link CastList }
     *     
     */
    public CastList getCast() {
        return cast;
    }

    /**
     * Sets the value of the cast property.
     * 
     * @param value
     *     allowed object is
     *     {@link CastList }
     *     
     */
    public void setCast(CastList value) {
        this.cast = value;
    }

    /**
     * Gets the value of the theaterReleaseDates property.
     * 
     * @return
     *     possible object is
     *     {@link TheaterReleaseDates }
     *     
     */
    public TheaterReleaseDates getTheaterReleaseDates() {
        return theaterReleaseDates;
    }

    /**
     * Sets the value of the theaterReleaseDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TheaterReleaseDates }
     *     
     */
    public void setTheaterReleaseDates(TheaterReleaseDates value) {
        this.theaterReleaseDates = value;
    }

    /**
     * Gets the value of the dvdReleaseDates property.
     * 
     * @return
     *     possible object is
     *     {@link DvdReleaseDates }
     *     
     */
    public DvdReleaseDates getDvdReleaseDates() {
        return dvdReleaseDates;
    }

    /**
     * Sets the value of the dvdReleaseDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DvdReleaseDates }
     *     
     */
    public void setDvdReleaseDates(DvdReleaseDates value) {
        this.dvdReleaseDates = value;
    }

    /**
     * Gets the value of the criticSummary property.
     * 
     * @return
     *     possible object is
     *     {@link CriticSummary }
     *     
     */
    public CriticSummary getCriticSummary() {
        return criticSummary;
    }

    /**
     * Sets the value of the criticSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriticSummary }
     *     
     */
    public void setCriticSummary(CriticSummary value) {
        this.criticSummary = value;
    }

    /**
     * Gets the value of the fanSummary property.
     * 
     * @return
     *     possible object is
     *     {@link FanSummary }
     *     
     */
    public FanSummary getFanSummary() {
        return fanSummary;
    }

    /**
     * Sets the value of the fanSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link FanSummary }
     *     
     */
    public void setFanSummary(FanSummary value) {
        this.fanSummary = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{}typedString" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class AlternateIds implements Serializable {

        @XmlElement(required = true)
        protected List<TypedString> id;

        /**
         * Gets the value of the id property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the id property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypedString }
         * 
         * 
         */
        public List<TypedString> getId() {
            if (id == null) {
                id = new ArrayList<TypedString>();
            }
            return this.id;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dvdReleaseDate" type="{}releaseDate" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dvdReleaseDate"
    })
    public static class DvdReleaseDates implements Serializable {

        @XmlElement(required = true)
        protected List<ReleaseDate> dvdReleaseDate;

        /**
         * Gets the value of the dvdReleaseDate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dvdReleaseDate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDvdReleaseDate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReleaseDate }
         * 
         * 
         */
        public List<ReleaseDate> getDvdReleaseDate() {
            if (dvdReleaseDate == null) {
                dvdReleaseDate = new ArrayList<ReleaseDate>();
            }
            return this.dvdReleaseDate;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="poster" type="{}sizedUrl" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "poster"
    })
    public static class Posters implements Serializable {

        @XmlElement(required = true)
        protected List<SizedUrl> poster;

        /**
         * Gets the value of the poster property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the poster property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPoster().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SizedUrl }
         * 
         * 
         */
        public List<SizedUrl> getPoster() {
            if (poster == null) {
                poster = new ArrayList<SizedUrl>();
            }
            return this.poster;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class SimilarMovies implements Serializable {

        @XmlElement(type = Long.class)
        protected List<Long> id;

        /**
         * Gets the value of the id property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the id property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getId() {
            if (id == null) {
                id = new ArrayList<Long>();
            }
            return this.id;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="theaterReleaseDate" type="{}releaseDate" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "theaterReleaseDate"
    })
    public static class TheaterReleaseDates implements Serializable {

        @XmlElement(required = true)
        protected List<ReleaseDate> theaterReleaseDate;

        /**
         * Gets the value of the theaterReleaseDate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the theaterReleaseDate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTheaterReleaseDate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReleaseDate }
         * 
         * 
         */
        public List<ReleaseDate> getTheaterReleaseDate() {
            if (theaterReleaseDate == null) {
                theaterReleaseDate = new ArrayList<ReleaseDate>();
            }
            return this.theaterReleaseDate;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="url" type="{}typedUrl" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "url"
    })
    public static class Urls implements Serializable {

        @XmlElement(required = true)
        protected List<TypedUrl> url;

        /**
         * Gets the value of the url property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the url property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUrl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypedUrl }
         * 
         * 
         */
        public List<TypedUrl> getUrl() {
            if (url == null) {
                url = new ArrayList<TypedUrl>();
            }
            return this.url;
        }

    }

}
