//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 03:47:41 PM GMT 
//


package com.echostar.model.partialVodAssets.jaxb;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRegistry;

import com.echostar.model.partialVodAssets.jaxb.CastList.Actors;
import com.echostar.model.partialVodAssets.jaxb.CastList.Directors;
import com.echostar.model.partialVodAssets.jaxb.Movie.AlternateIds;
import com.echostar.model.partialVodAssets.jaxb.Movie.DvdReleaseDates;
import com.echostar.model.partialVodAssets.jaxb.Movie.Posters;
import com.echostar.model.partialVodAssets.jaxb.Movie.SimilarMovies;
import com.echostar.model.partialVodAssets.jaxb.Movie.TheaterReleaseDates;
import com.echostar.model.partialVodAssets.jaxb.Movie.Urls;
import com.echostar.model.partialVodAssets.jaxb.PartialVodAsset.Reviews;
import com.echostar.model.partialVodAssets.jaxb.PartialVodAsset.VodRecommendations;
import com.echostar.model.partialVodAssets.jaxb.VodReco.Recommendations;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.echostar.model.partialVodAssets.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.echostar.model.partialVodAssets.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CastList }
     * 
     */
    public CastList createCastList() {
        return new CastList();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link FanSummary }
     * 
     */
    public FanSummary createFanSummary() {
        return new FanSummary();
    }

    /**
     * Create an instance of {@link CriticSummary }
     * 
     */
    public CriticSummary createCriticSummary() {
        return new CriticSummary();
    }

    /**
     * Create an instance of {@link Directors }
     * 
     */
    public Directors createCastListDirectors() {
        return new Directors();
    }

    /**
     * Create an instance of {@link com.echostar.model.partialVodAssets.jaxb.Freshness }
     * 
     */
    public com.echostar.model.partialVodAssets.jaxb.Freshness createFreshness() {
        return new com.echostar.model.partialVodAssets.jaxb.Freshness();
    }

    /**
     * Create an instance of {@link Actors }
     * 
     */
    public Actors createCastListActors() {
        return new Actors();
    }

    /**
     * Create an instance of {@link PartialVodAsset }
     * 
     */
    public PartialVodAsset createPartialVodAsset() {
        return new PartialVodAsset();
    }

    /**
     * Create an instance of {@link TheaterReleaseDates }
     * 
     */
    public TheaterReleaseDates createMovieTheaterReleaseDates() {
        return new TheaterReleaseDates();
    }

    /**
     * Create an instance of {@link SizedUrl }
     * 
     */
    public SizedUrl createSizedUrl() {
        return new SizedUrl();
    }

    /**
     * Create an instance of {@link Recommendation }
     * 
     */
    public Recommendation createRecommendation() {
        return new Recommendation();
    }

    /**
     * Create an instance of {@link Recommendations }
     * 
     */
    public Recommendations createVodRecoRecommendations() {
        return new Recommendations();
    }

    /**
     * Create an instance of {@link Urls }
     * 
     */
    public Urls createMovieUrls() {
        return new Urls();
    }

    /**
     * Create an instance of {@link VodReco }
     * 
     */
    public VodReco createVodReco() {
        return new VodReco();
    }

    /**
     * Create an instance of {@link SimilarMovies }
     * 
     */
    public SimilarMovies createMovieSimilarMovies() {
        return new SimilarMovies();
    }

    /**
     * Create an instance of {@link ReleaseDate }
     * 
     */
    public ReleaseDate createReleaseDate() {
        return new ReleaseDate();
    }

    /**
     * Create an instance of {@link DvdReleaseDates }
     * 
     */
    public DvdReleaseDates createMovieDvdReleaseDates() {
        return new DvdReleaseDates();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link Posters }
     * 
     */
    public Posters createMoviePosters() {
        return new Posters();
    }

    /**
     * Create an instance of {@link TypedUrl }
     * 
     */
    public TypedUrl createTypedUrl() {
        return new TypedUrl();
    }

    /**
     * Create an instance of {@link com.echostar.model.partialVodAssets.jaxb.CriticSummary.Score }
     * 
     */
    public com.echostar.model.partialVodAssets.jaxb.CriticSummary.Score createCriticSummaryScore() {
        return new com.echostar.model.partialVodAssets.jaxb.CriticSummary.Score();
    }

    /**
     * Create an instance of {@link com.echostar.model.partialVodAssets.jaxb.FanSummary.Score }
     * 
     */
    public com.echostar.model.partialVodAssets.jaxb.FanSummary.Score createFanSummaryScore() {
        return new com.echostar.model.partialVodAssets.jaxb.FanSummary.Score();
    }

    /**
     * Create an instance of {@link AlternateIds }
     * 
     */
    public AlternateIds createMovieAlternateIds() {
        return new AlternateIds();
    }

    /**
     * Create an instance of {@link VodRecommendations }
     * 
     */
    public VodRecommendations createPartialVodAssetVodRecommendations() {
        return new VodRecommendations();
    }

    /**
     * Create an instance of {@link PartialVodAssets }
     * 
     */
    public PartialVodAssets createPartialVodAssets() {
        return new PartialVodAssets();
    }

    /**
     * Create an instance of {@link Movies }
     * 
     */
    public Movies createMovies() {
        return new Movies();
    }

    /**
     * Create an instance of {@link com.echostar.model.partialVodAssets.jaxb.CriticSummary.Freshness }
     * 
     */
    public com.echostar.model.partialVodAssets.jaxb.CriticSummary.Freshness createCriticSummaryFreshness() {
        return new com.echostar.model.partialVodAssets.jaxb.CriticSummary.Freshness();
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link TypedString }
     * 
     */
    public TypedString createTypedString() {
        return new TypedString();
    }

    /**
     * Create an instance of {@link Reviews }
     * 
     */
    public Reviews createPartialVodAssetReviews() {
        return new Reviews();
    }

    /**
     * Create an instance of {@link Publication }
     * 
     */
    public Publication createPublication() {
        return new Publication();
    }

}
